# Build with docker compose build --build-arg id=...
---
services:
  meshcentral:
    container_name: meshcentral
    image: meshcentral:dev
    build: ./
    network_mode: bridge
    restart: unless-stopped
    privileged: false
    security_opt: [no-new-privileges:true]
    volumes:
      - ${nfsvols}/meshcentral:/opt/meshcentral/meshcentral-data
    ports:
      - 1100:1100
      - 4433:4433
      - 9971:9971
