---
services:
  speedtest:
    image: ghcr.io/linuxserver/librespeed:latest
    container_name: librespeed
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    network_mode: bridge
    ports:
      - 8082:80
