version: '3.8'

networks:
  traefik-internal:
    external: true
    name: traefik-internal

services:
  speedtest:
    image: ghcr.io/linuxserver/librespeed:latest
    container_name: librespeed
    restart: unless-stopped
    networks: [traefik-internal]
    security_opt: [no-new-privileges:true]
    labels:
      traefik.enable: true
      traefik.http.routers.librespeed.tls: true
      traefik.http.routers.librespeed.service: librespeed
      traefik.http.services.librespeed.loadbalancer.server.port: 80
      traefik.http.routers.librespeed.middlewares: secure-headers@file,rateLimit@file
