---
volumes:
  frigate-recordings:
    name: frigate-recordings
    driver_opts:
      type: nfs
      o: addr=${remote_storage_server},nfsvers=4.2,soft,nolock,rw
      device: ":${remote_slow_location}/apps/frigate"

networks:
  internal-iot-vlan:
    name: ${iot_net_name}
    driver: macvlan
    driver_opts:
      parent: vlan${iot_net_vlan}
    ipam:
      driver: default
      config:
        - subnet: ${iot_net_subnet}
          gateway: ${iot_net_gateway}

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.17.0
    container_name: frigate
    restart: unless-stopped
    # https://docs.frigate.video/configuration/hardware_acceleration_video/#configuring-intel-gpu-stats-in-docker
    # Run privileged to allow access to iGPU metrics (the kernel.perf_event_paranoid setting did not fix this)
    privileged: true
    security_opt: [no-new-privileges:true]
    shm_size: 512m
    tmpfs: /tmp/cache:size=500m # reduces SSD/SD Card wear
    devices:
      # - /dev/apex_0 # PCI Coral TPU (object detection)
      - /dev/dri/renderD128 # Intel iGPU can handle both video decode and object detection
    volumes:
      - ${local_apps_location}/frigate/config.yml:/config/config.yml
      - ${local_apps_location}/frigate:/media/frigate
      - frigate-recordings:/media/frigate/recordings
    networks:
      internal-iot-vlan:
        ipv4_address: ${frigate_ip}
    environment:
      TZ: ${TZ}
      FRIGATE_RTSP_PASSWORD: ${frigate_rtsp_password}
      FRIGATE_MQTT_USER: frigate
      FRIGATE_MQTT_PASSWORD: ${frigate_mqtt_password}
