---
- hosts: "oci"
  gather_facts: false
  become: true
  
  vars:
    ansible_port: 41500
    infrastructure: oci

  pre_tasks:
    - ansible.builtin.import_tasks: "../tasks/load_ssh_key.yml"

  tasks:
    - name: "Pinger"
      ping:

    # OCI image gives a Ubuntu user that we only use to setup the Ansible user
    - name: "SSH - Remove default SSH key"
      ansible.posix.authorized_key:
        user: "ubuntu"
        state: "absent"
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIt6Xfre05KU/vnKTTN07E0qG9n2nLVwgZQ7xZdw8IOp Ansible - 01FEB2023"

    # - name: "SSH - Only listen on wg0 - Cloud Servers"
    #   ansible.builtin.replace:
    #     path: "/etc/ssh/sshd_config"
    #     regexp: '^(ListenAddress[ ]+)[^\n]+$'
    #     replace: '\g<1>{{ wg_ip }}'
    #   when: infrastructure == 'oci'

    - name: "SSH - Add wg0 as sshd dependency - Cloud Servers"
      ansible.builtin.blockinfile:
        path: "/etc/systemd/system/sshd.service"
        insertafter: "\\[Unit\\]"
        block: |
          After=network.target wg-quick@wg0.service
          Requires=sys-devices-virtual-net-wg0.device
      when: infrastructure == 'oci'

  post_tasks:
    - ansible.builtin.import_tasks: "../tasks/unload_ssh_key.yml"
...