---
- name: "SSH - Configure sshd"
  ansible.builtin.template: 
    src: "../templates/sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    validate: '/usr/sbin/sshd -T -f %s'
  register: sshd_updated

- name: "SSH - Restart sshd if needed"
  ansible.builtin.systemd:
    name: "sshd"
    state: "reloaded"
  when: sshd_updated.changed
...