---
- become: false
  delegate_to: "ansible"
  no_log: true
  run_once: true
  block:
  - name: "Postload - Unload SSH key from ssh-agent"
    ansible.builtin.command: "ssh-add -d {{ ssh_private_key_file }}"
    changed_when: false
    register: postload_output
    failed_when:
    - "'Could not remove identity' not in postload_output.stderr"
    - "'Identity removed' not in postload_output.stderr"

  - name: "Postload - Remove SSH key from localhost"
    ansible.builtin.file:
      path: "{{ ssh_private_key_file }}"
      state: "absent"
    changed_when: false
...