---
services:
  Guac:
    image: oznu/guacamole:armhf
    container_name: Guacamole
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    volumes:
      - GuacData:/config
    ports:
      - 80:8080
    networks:
      macvlanXXX:
        ipv4_address: x.x.x.x
    labels:
      - "traefik.enable=false"

volumes:
  GuacData:
    external: true

networks:
  macvlanXXX:
    external: true
