---
- name: "Add the nvidia-container-toolkit repo"
  ansible.builtin.get_url:
    dest: "/etc/yum.repos.d/nvidia-container-toolkit.repo"
    mode: "0644"
    url: "https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo"

- name: "Install GPU-related rpm-ostree packages"
  community.general.rpm_ostree_pkg:
    name:
      # Nvidia drivers
      - "akmod-nvidia"
      - "xorg-x11-drv-nvidia-cuda"
      - "nvidia-container-toolkit"
      # Utils useful for Nvidia GPU stuff
      - "python3-pip"
      - "pciutils" # lspci
      - "lshw"
      - "nvtop"
  notify: "Reboot Server"

- name: "Run handlers"
  ansible.builtin.meta: flush_handlers

- name: "Install pip packages"
  ansible.builtin.pip:
    name: gpustat

- name: "Disable the nvidia-powerd service"
  ansible.builtin.systemd_service:
    enabled: false
    name: "nvidia-powerd.service"
  notify: "Reboot Server"

- name: "Run handlers"
  ansible.builtin.meta: flush_handlers

- name: "Get stats on /etc/cdi/nvidia.yaml"
  ansible.builtin.stat:
    path: "/etc/cdi/nvidia.yaml"
  register: nvidia_cdi_config

- name: "Generate Nvidia CDI config"
  ansible.builtin.command: "nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml"
  changed_when: false
  when: nvidia_cdi_config.stat.exists is defined and not nvidia_cdi_config.stat.exists

- name: "Verify the Nvidia CDI config"
  ansible.builtin.command: "nvidia-ctk cdi list"
  changed_when: false
  failed_when: "'nvidia.com/gpu=0' not in nvidia_cdi_verify.stdout"
  register: nvidia_cdi_verify

- name: "Check Nvidia config in /etc/docker/daemon.json"
  ansible.builtin.command: grep -q nvidia-container-runtime /etc/docker/daemon.json
  register: nvidia_docker_config
  changed_when: nvidia_docker_config.rc in [1, 2]
  failed_when: nvidia_docker_config.rc not in [0, 1, 2]

- name: "Generate Nvidia Docker config"
  ansible.builtin.command: "nvidia-ctk runtime configure --runtime=docker"
  notify: "Reload Docker service"
  register: nvidia_docker_config_generated
  when: nvidia_docker_config.changed

- name: "Run handlers"
  ansible.builtin.meta: flush_handlers

- name: "Create systemd task to generate CTK config at boot"
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Nvidia CDI Config Generator

      [Service]
      Type=oneshot
      ExecStart=nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml

      [Install]
      WantedBy=multi-user.target docker.socket
    dest: "/etc/systemd/system/nvidia-cdi-gen.service"
    mode: "0644"

- name: "Enable Nvidia CDI generation task"
  ansible.builtin.systemd_service:
    name: "nvidia-cdi-gen.service"
    enabled: true
...
