---
networks:
  external-bridge:
    name: external-bridge

services:
  dashy:
    image: ghcr.io/lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped
    privileged: false
    security_opt: [no-new-privileges:true]
    environment:
      NODE_ENV: production
    volumes:
      - ${local_apps_location}/dashy/conf.yml:/app/user-data/conf.yml
      - ${local_apps_location}/dashy/icons:/app/user-data/item-icons
      - ${local_apps_location}/dashy/JetBrainsMono-Regular.ttf:/app/user-data/fonts/JetBrainsMono-Regular.ttf
    networks: [external-bridge]
    ports:
      - 8081:8080
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      start_period: 10s
