---
networks:
  external-bridge:
    name: external-bridge
    external: true
  internal-mealie:
    name: internal-mealie
    internal: true

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.2.1
    container_name: mealie
    restart: always
    privileged: false
    security_opt: [no-new-privileges:true]
    networks: [external-bridge, internal-mealie]
    ports:
      - 9001:9000
    volumes:
      - ${nfs_fast_apps}/mealie/app:/app/data/
    environment:
      BASE_URL: https://recipes.${DOMAIN}
      TOKEN_TIME: 4
      MAX_WORKERS: 4
      ALLOW_SIGNUP: false
      # PUID: ${NFS_PUID}
      # PGID: ${NFS_PGID}
      TZ: ${TZ}
      WEB_CONCURRENCY: 1
      DB_ENGINE: postgres
      POSTGRES_SERVER: mealie-db
      POSTGRES_DB: mealie
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: ${MEALIE_DB_PASSWORD}
    depends_on:
      mealie-db:
        condition: service_healthy

  mealie-db:
    container_name: mealie-db
    image: postgres:15
    restart: always
    privileged: false
    security_opt: [no-new-privileges:true]
    networks: [internal-mealie]
    volumes:
      - ${nfs_fast_apps}/mealie/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mealie
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: ${MEALIE_DB_PASSWORD}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER
      interval: 30s
      timeout: 20s
      retries: 3
