---
networks:
  external-bridge:
    name: external-bridge
  internal-unifi:
    name: internal-unifi
    internal: true

volumes:
  unifi-db-configdb:
    name: unifi-db-configdb

services:
  unifi-network:
    image: lscr.io/linuxserver/unifi-network-application:10.1.89
    container_name: unifi-network
    restart: unless-stopped
    privileged: false
    security_opt: [no-new-privileges:true]
    volumes:
      - ${local_apps_location}/unifi/app:/config
    networks: [external-bridge, internal-unifi]
    ports:
      - 3478:3478/udp # STUN
      - 8080:8080 # device-to-controller communication
      - 8443:8443 # web ui
    environment:
      MEM_LIMIT: 1024
      MEM_STARTUP: 1024
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
    depends_on:
      unifi-db:
        condition: service_healthy

  # Locked to 4.4.18 to support raspberry pi 4
  unifi-db:
    image: mongo:4.4.18
    container_name: unifi-db
    restart: unless-stopped
    privileged: false
    security_opt: [no-new-privileges:true]
    volumes:
      - ${local_apps_location}/unifi/db:/data/db
      - unifi-db-configdb:/data/configdb
    networks: [internal-unifi]
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin --quiet | grep 1
      start_period: 5s
