version: '3'

networks:
  homeassistant-internal:
    name: homeassistant-internal
  iot:
    name: ${iot_net_name}
    driver: macvlan
    driver_opts:
      parent: eno1.${iot_net_vlan}
    ipam:
      driver: default
      config:
        - subnet: ${iot_net_subnet}
          gateway: ${iot_net_gateway}

services:
  hass-diag-pgadmin:
    image: dpage/pgadmin4:7
    container_name: hass-diag-pgadmin
    restart: unless-stopped
    networks: [homeassistant-internal]
    ports:
      - 5434:80
    privileged: false
    security_opt: [no-new-privileges:true]
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DISABLE_POSTFIX: true

# Manually update gen1 Shelly devices by starting this webserver to host the firmware and triggering it vie:
# http://IP_OF_RELAY/ota?url=http://${shelly-ip}/SHSW-25-1.14.0.zip

# htaccess content:
# Alias 'shelly25' '/usr/local/apache2/htdocs/SHSW-25-1.14.0.zip'
  shelly-fw-updater:
    image: httpd:2.4
    container_name: shelly-fw-updater
    volumes:
      - ${HOME}/shelly:/usr/local/apache2/htdocs/
      - ${HOME}/htaccess:/usr/local/apache2/.htaccess
    networks:
      iot:
        ipv4_address: ${shelly-ip}
