version: '3'

secrets:
  grafana_admin_password:
    file: ${nfssecrets}/grafana_admin_password

networks:
  iot:
    name: ${iot_net_name}
    driver: macvlan
    driver_opts:
      parent: eno1.${iot_net_vlan}
    ipam:
      driver: default
      config:
        - subnet: ${iot_net_subnet}
          gateway: ${iot_net_gateway}
  home:
    name: ${home_net_name}
    driver: macvlan
    driver_opts:
      parent: eno1.${home_net_vlan}
    ipam:
      driver: default
      config:
        - subnet: ${home_net_subnet}
          gateway: ${home_net_gateway}
  homeassistant-internal:
    external: false
    internal: true
    name: homeassistant-internal
  internet-bridge:
    external: true
    name: internet-bridge
  traefik-internal:
    external: true
    name: traefik-internal
  traefik:
    external: true
    name: traefik

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2024.6
    container_name: homeassistant
    restart: unless-stopped
    privileged: false
    security_opt: [no-new-privileges:true]
    depends_on: [homeassistant-db]
    environment:
      TZ: ${TZ}
    volumes:
      - ${nfsvols}/hass/config:/config
    networks:
      home:
        ipv4_address: ${homeassistant_home_ip}
      iot:
        ipv4_address: ${homeassistant_iot_ip}
      homeassistant-internal:
      # internet-bridge:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.homeassistant.tls: true
      traefik.http.routers.homeassistant.service: homeassistant
      traefik.http.services.homeassistant.loadbalancer.server.port: 8123
      traefik.docker.network: traefik
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  homeassistant-db:
    image: timescale/timescaledb-ha:pg15
    container_name: homeassistant-db
    restart: unless-stopped
    user: ${NFS_PUID}:${NFS_PGID}
    privileged: false
    security_opt: [no-new-privileges:true]
    networks: [homeassistant-internal]
    volumes:
      - ${nfsvols}/hass/db:/home/postgres/pgdata

  # Port: 1883
  # To add user, in container: mosquitto_passwd -b /mosquitto/config/mqttuser username password
  homeassistant-mqtt:
    image: eclipse-mosquitto:2.0.18
    container_name: homeassistant-mqtt
    restart: unless-stopped
    # network_mode: "container:homeassistant"
    # depends_on: [homeassistant]
    networks: [homeassistant-internal]
    user: ${NFS_PUID}:${NFS_PGID}
    privileged: false
    security_opt: [no-new-privileges:true]
    volumes:
      - ${nfsvols}/hass/mqtt/config:/mosquitto/config
      - ${nfsvols}/hass/mqtt/data:/mosquitto/data
      - ${nfsvols}/hass/mqtt/log:/mosquitto/log

  # Port: 6052
  homeassistant-esphome:
    image: ghcr.io/esphome/esphome:2024.5
    container_name: homeassistant-esphome
    restart: unless-stopped
    networks:
      iot:
        ipv4_address: ${esphome_ip}
      traefik-internal:
    privileged: false
    security_opt: [no-new-privileges:true]
    environment:
      ESPHOME_DASHBOARD_USE_PING: true
      USERNAME: ${ESPHOME_USER}
      PASSWORD: ${ESPHOME_PASSWORD}
    labels:
      traefik.enable: true
      traefik.http.routers.esphome.tls: true
      traefik.http.routers.esphome.service: esphome
      traefik.http.services.esphome.loadbalancer.server.port: 6052
      traefik.http.routers.esphome.rule: Host(`esphome.${DOMAIN}`)
    volumes:
      - ${nfsvols}/hass/esphome:/config

  # Port: 8080
  homeassistant-zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.38.0
    container_name: homeassistant-zigbee2mqtt
    restart: unless-stopped
    networks:
      iot:
        ipv4_address: ${zigbee2mqtt_ip}
      traefik:
      homeassistant-internal:
    user: ${NFS_PUID}:${NFS_PGID}
    privileged: false
    security_opt: [no-new-privileges:true]
    environment:
      TZ: ${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.zigbee2mqtt.tls: true
      traefik.http.routers.zigbee2mqtt.service: zigbee2mqtt
      traefik.http.services.zigbee2mqtt.loadbalancer.server.port: 8080
      traefik.http.routers.zigbee2mqtt.rule: Host(`zigbee2mqtt.${DOMAIN}`)
      traefik.docker.network: traefik
    volumes:
      - ${nfsvols}/hass/zigbee2mqtt:/app/data

  grafana:
    image: grafana/grafana-enterprise:10.2.7
    container_name: grafana
    restart: unless-stopped
    privileged: false
    security_opt: [no-new-privileges:true]
    networks: [homeassistant-internal]
    ports:
     - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
      # GF_SERVER_ROOT_URL: http://my.grafana.server/
      # GF_INSTALL_PLUGINS: grafana-clock-panel
    secrets:
      - grafana_admin_password
    volumes:
      - ${nfsvols}/grafana:/var/lib/grafana

  # Port: 1880
  # homeassistant-node-red:
  #   image: nodered/node-red:3.1
  #   container_name: homeassistant-node-red
  #   restart: unless-stopped
  #   network_mode: "container:homeassistant"
  #   user: ${NFS_PUID}:${NFS_PGID}
  #   privileged: false
  #   security_opt: [no-new-privileges:true]
  #   volumes:
  #     - ${nfsvols}/hass/nodered:/data

  # Port: 8080
  # homeassistant-vscode:
  #   image: codercom/code-server:debian
  #   container_name: homeassistant-vscode
  #   restart: unless-stopped
  #   network_mode: "container:homeassistant"
  #   user: ${NFS_PUID}:${NFS_PGID}
  #   privileged: false
  #   security_opt: [no-new-privileges:true]
  #   volumes:
  #     # Set <project dir> to the directory you want to open in VS Code.
  #     - <project dir>:/home/coder/project
  #     # <vs code config> should point to a local dir where vs code stores its data.
  #     - <vs code config dir>:/home/coder/.local/share/code-server
  #   command: code-server --auth password --disable-telemetry /home/coder/project
  #   environment:
  #     PASSWORD: "${VSCODE_PASSWORD}"
