---
networks:
  external-home-vlan:
    name: ${home_net_name}
    driver: macvlan
    driver_opts:
      parent: vlan${home_net_vlan}
    ipam:
      config:
        - subnet: ${home_net_subnet}
          gateway: ${home_net_gateway}
  external-bridge:
    name: external-bridge
  internal-homeassistant:
    name: internal-homeassistant
    internal: true
  internal-iot-vlan:
    name: ${iot_net_name}
    driver: macvlan
    external: true
    driver_opts:
      parent: vlan${iot_net_vlan}
    ipam:
      config:
        - subnet: ${iot_net_subnet}
          gateway: ${iot_net_gateway}

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.3
    container_name: homeassistant
    restart: unless-stopped
    privileged: false
    security_opt: [no-new-privileges:true]
    depends_on: [homeassistant-db]
    environment:
      TZ: ${TZ}
    volumes:
      - ${local_apps_location}/homeassistant/app:/config
    networks:
      # external-home-vlan must be first for Apple Homekit to work
      external-home-vlan:
        ipv4_address: ${homeassistant_home_ip}
      internal-iot-vlan:
        ipv4_address: ${homeassistant_iot_ip}
      internal-homeassistant:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      start_period: 15s

  homeassistant-db:
    image: timescale/timescaledb-ha:pg15.14-ts2.21.3
    container_name: homeassistant-db
    restart: unless-stopped
    user: ${apps_user}
    privileged: false
    security_opt: [no-new-privileges:true]
    networks: [internal-homeassistant]
    volumes:
      - ${local_apps_location}/homeassistant/db:/home/postgres/pgdata

  # Port: 1883
  # To add user, in container: mosquitto_passwd -b /mosquitto/config/mqttuser username password
  homeassistant-mqtt:
    image: eclipse-mosquitto:2.1.2-alpine
    container_name: homeassistant-mqtt
    restart: unless-stopped
    networks: [internal-homeassistant]
    privileged: false
    security_opt: [no-new-privileges:true]
    volumes:
      - ${local_apps_location}/homeassistant/mqtt/config:/mosquitto/config
      - ${local_apps_location}/homeassistant/mqtt/data:/mosquitto/data
      - ${local_apps_location}/homeassistant/mqtt/log:/mosquitto/log

  homeassistant-esphome:
    image: ghcr.io/esphome/esphome:2026.3
    container_name: homeassistant-esphome
    restart: unless-stopped
    networks:
      # internet-capable network must be first to download resources
      external-bridge:
      internal-iot-vlan:
        ipv4_address: ${esphome_ip}
    ports:
      - 6052:6052
    privileged: false
    security_opt: [no-new-privileges:true]
    environment:
      ESPHOME_DASHBOARD_USE_PING: true
      USERNAME: ${ESPHOME_USER}
      PASSWORD: ${ESPHOME_PASSWORD}
    volumes:
      - ${local_apps_location}/homeassistant/esphome:/config

  # Port: 8080
  homeassistant-zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2.9.1
    container_name: homeassistant-zigbee2mqtt
    restart: unless-stopped
    networks:
      # internet-capable network must be first if I want Z2M to search for firmware updates
      internal-homeassistant:
      internal-iot-vlan:
        ipv4_address: ${zigbee2mqtt_ip}
    privileged: false
    security_opt: [no-new-privileges:true]
    environment:
      TZ: ${TZ}
    volumes:
      - ${local_apps_location}/homeassistant/zigbee2mqtt:/app/data

  # musicassistant:
  #   image: ghcr.io/music-assistant/server:2.5.8
  #   volumes:
  #     - ${local_apps_location}/homeassistant/musicassistant:/data
  #   networks:
  #     external-home-vlan:
  #       ipv4_address: ${musicassistant_home_ip} # TODO: Create this IP
  #     internal-homeassistant:

  # grafana:
  #   image: grafana/grafana-enterprise:10.2.7
  #   container_name: grafana
  #   restart: unless-stopped
  #   privileged: false
  #   security_opt: [no-new-privileges:true]
  #   networks: [internal-homeassistant]
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
  #     # GF_SERVER_ROOT_URL: http://my.grafana.server/
  #     # GF_INSTALL_PLUGINS: grafana-clock-panel
  #   volumes:
  #     - ${local_apps_location}/homeassistant/grafana:/var/lib/grafana
